nginx:
  image: nginx:1.12-alpine
  ports:
    - "80:80"
    - "443:443"
  links:
    - "php"
  volumes:
    - /home/docker/webroot:/usr/share/nginx/html
    - /home/docker/log/nginx/log:/usr/share/nginx/log
    # web configs
    - /home/docker/.conf/nginx/conf.d:/etc/nginx/conf.d

php:
  build: ./container/php
  dockerfile: Dockerfile-5.6-fpm-alpine
  ports:
    - "9000:9000"
    - "9001:9001"
    - "2222:22"
  links:
    - "percona"
    - "memcache"
    - "redis"
  volumes:
    - /home/docker/webroot:/var/www/html
    - /home/docker/log/php/log:/var/www/log
  environment:
    COMPOSER_PACKAGIST: 'https://packagist.phpcomposer.com'
    XDEBUG_REMOTE_ENABLE: "yes"
    XDEBUG_REMOTE_PORT: 9001

percona:
  image: percona:5.6
  ports:
    - "3306:3306"
  volumes:
    - /home/docker/.database/percona:/var/lib/mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

memcache:
  image: memcached:1.5-alpine
  ports:
    - "11211:11211"

redis:
  image: redis:3.2-alpine
  ports:
    - "6379:6379"

