#!/bin/bash
set -xe

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
    readonly PHP_RUN="$@"
else
    readonly PHP_RUN="php-fpm"
fi

# ssh
if [ "${SSH_ENABLED}" == 'yes' ];then
    # set root passowrd in env
    if [ ${#SSH_ROOT_PASSWORD} -gt 5 ]; then
        echo "root:${SSH_ROOT_PASSWORD}" | chpasswd
    fi

    # ssh start
    #mkdir -p /var/run/sshd
    #/usr/sbin/sshd -De
    service ssh start
fi

if [ "${XDEBUG_REMOTE_ENABLE}" == 'yes' ]; then
    # php remote debug config
    readonly XDEBUG_CONF=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    if [ -f "${XDEBUG_CONF}" ]; then
        echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so" > ${XDEBUG_CONF}
        #echo "xdebug.idekey=PHPSTORM" >> ${XDEBUG_CONF}
        echo "xdebug.remote_enable=1" >> ${XDEBUG_CONF}
        #echo "xdebug.remote_host=192.168.188.105" >> ${XDEBUG_CONF}
        echo "xdebug.remote_port=${XDEBUG_REMOTE_PORT:-9001}" >> ${XDEBUG_CONF}
        echo "xdebug.profiler_enable=1" >> ${XDEBUG_CONF}
        echo "xdebug.remote_connect_back=1" >> ${XDEBUG_CONF}
        echo "xdebug.scream=0" >> ${XDEBUG_CONF}
        echo "xdebug.cli_color=1" >> ${XDEBUG_CONF}
        echo "xdebug.show_local_vars=1" >> ${XDEBUG_CONF}
    else
        printf "no found xdebug.ini \n"
    fi
fi

#php-fpm
exec "$PHP_RUN"
