FROM php:5.6-fpm

LABEL maintainer="Royee <ms_save95@126.com>"

# source files
COPY . /home/tmp/

# composer profile
ENV PATH="~/.composer/vendor/bin:$PATH" \
    COMPOSER_ALLOW_SUPERUSER=1

RUN set -xe \
    # move sources.list & php.ini
    && mv /home/tmp/config/sources.list /etc/apt/sources.list \
    && mv /home/tmp/config/php56.ini-production  /usr/local/etc/php/php.ini \
    \
    # set argument & install compiling env
    && buildDeps=" \
        git \
        libgearman-dev \
        libmemcached-dev \
        libmcrypt-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng12-dev \
    " \
    && runtimeDeps=" \
        libfreetype6 \
        libjpeg62-turbo \
        libmcrypt4 \
        libpng12-0 \
    " \
    && apt-get update && apt-get install -y $buildDeps $runtimeDeps --no-install-recommends \
    \
    # install PHP extensions
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install gd \
    && docker-php-ext-install zip mcrypt pdo_mysql \
    && pecl install /home/tmp/download/redis.tgz && docker-php-ext-enable redis \
    && pecl install /home/tmp/download/memcache.tgz && docker-php-ext-enable memcache \
    && pecl install /home/tmp/download/xhprof.tgz && docker-php-ext-enable xhprof \
    && pecl install /home/tmp/download/xdebug.tgz && docker-php-ext-enable xdebug \
    \
    # clear
    && apt-get purge -y --auto-remove \
        -o APT::AutoRemove::RecommendsImportant=false \
        -o APT::AutoRemove::SuggestsImportant=false \
        $buildDeps \
    && rm -rf /var/cache/apt/* \
    && rm -rf /var/lib/apt/lists/* \
    \
    # Composer
    && mv /home/tmp/download/composer.phar /usr/local/bin/composer \
    && chmod 755 /usr/local/bin/composer \
    # && composer self-update \
    && composer --ansi --version --no-interaction \
    # china composer packagist
    && composer config -g repo.packagist composer https://packagist.laravel-china.org \
    # install laravelInstaller
    && composer global require "laravel/installer" \
    && ~/.composer/vendor/bin/laravel --version \
    && composer clear-cache \
    \
    # clear
    && rm -rf /home/tmp \
    \
    # write permission
    && usermod -u 1000 www-data

