php56:
  build: ../container/php
  dockerfile: Dockerfile-5.6-phpstorm
  volumes:
    - /Users/royee/Develop/Medlinker:/var/www/html
    - /Users/royee/.docker.local/logs/php/log:/var/www/log
    - /Users/royee/.docker.local/configs/php/php.ini:/usr/local/etc/php/php.ini

medlinker:
  build: ../container/php
  dockerfile: Dockerfile-medlinker-cli
  volumes:
    - /Users/royee/Develop/Medlinker:/var/www/html
    - /Users/royee/.docker.local/logs/php/log:/var/www/log
    - /Users/royee/.docker.local/configs/php/php.ini:/usr/local/etc/php/php.ini
