version: "2.2"
services:

  nginx:
    image: nginx:1.12-alpine
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    volumes:
      - {WEB_ROOT}:/usr/share/nginx/html
      - {HOME}/.docker.local/logs/nginx/log:/usr/share/nginx/log
      # web configs
      - {HOME}/.docker.local/configs/nginx/conf.d:/etc/nginx/conf.d

  php:
    build:
      context: ../container/php
      dockerfile: Dockerfile-5.6-fpm-alpine
    ports:
      - "9000:9000"
    links:
      - "percona"
      - "memcache"
      - "redis"
    volumes:
      - {WEB_ROOT}:/var/www/html
      - {HOME}/.docker.local/logs/php/log:/var/www/log
      - {HOME}/.docker.local/configs/php/php.ini:/usr/local/etc/php/php.ini
      - {HOME}/.docker.local/configs/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - {HOME}/.docker.local/configs/.ssh:/root/.ssh
    environment:
      COMPOSER_PACKAGIST: 'https://packagist.laravel-china.org'
      SSH_ENABLED: "no"
      SSH_ROOT_PASSWORD: 123456
    entrypoint: docker-entrypoint

  percona:
    image: percona:5.6
    ports:
      - "3306:3306"
    volumes:
      - {HOME}/.docker.local/.databases/percona:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  memcache:
    image: memcached:1.5-alpine
    ports:
      - "11211:11211"

  redis:
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
