#!/bin/bash
set -xe

printf "  entrypoint.... \n"
printf "  SSH_ENABLED: ${SSH_ENABLED} \n"
printf "  SSH_ROOT_PASSWORD: ${SSH_ROOT_PASSWORD} \n"
printf "  XDEBUG_REMOTE_ENABLED: ${XDEBUG_REMOTE_ENABLED} \n"
printf "  LARAVEL_ENABLED: ${LARAVEL_ENABLED} \n"

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
    set -- php-fpm "$@"
    readonly PHP_RUN="$@"
else
    readonly PHP_RUN="php-fpm"
fi

# ssh
if [ "${SSH_ENABLED}" == 'yes' ]; then
    printf "> Configure & Start ssh... \n"
    # set root passowrd in env
    if [ ${#SSH_ROOT_PASSWORD} -gt 5 ]; then
        echo "root:${SSH_ROOT_PASSWORD}" | chpasswd
        printf "  root user password has been changed to: \E[1m\E[32m${SSH_ROOT_PASSWORD}\E[0m \n"
    fi

    # ssh start
    #mkdir -p /var/run/sshd
    #/usr/sbin/sshd -De
    service ssh start
fi

# xdebug
if [ "${XDEBUG_REMOTE_ENABLED}" == 'yes' ]; then
    printf "> Configure xdebug... \n"
    # php remote debug config
    readonly XDEBUG_CONF=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    if [ -f "${XDEBUG_CONF}" ]; then
        echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so" > ${XDEBUG_CONF}
        #echo "xdebug.idekey=PHPSTORM" >> ${XDEBUG_CONF}
        echo "xdebug.remote_enable=1" >> ${XDEBUG_CONF}
        #echo "xdebug.remote_host=192.168.188.105" >> ${XDEBUG_CONF}
        echo "xdebug.remote_port=${XDEBUG_REMOTE_PORT:-9001}" >> ${XDEBUG_CONF}
        echo "xdebug.profiler_enable=1" >> ${XDEBUG_CONF}
        echo "xdebug.remote_connect_back=1" >> ${XDEBUG_CONF}
        echo "xdebug.scream=0" >> ${XDEBUG_CONF}
        echo "xdebug.cli_color=1" >> ${XDEBUG_CONF}
        echo "xdebug.show_local_vars=1" >> ${XDEBUG_CONF}

        printf "  \E[32m[SUCESS]\E[0m xdebug started. PROT: \E[1m${XDEBUG_REMOTE_PORT:-9001}\E[0m \n"
    else
        printf "  \E[31m[ERROR ]\E[0m no found xdebug.ini \n"
    fi
fi

# laravel
if [ "${LARAVEL_ENABLED}" == 'yes' ]; then
    /usr/local/bin/composer self-update
    # laravel installer
    /usr/local/bin/composer global require "laravel/installer"
    ~/.composer/vendor/bin/laravel --version
fi

# php-fpm
printf "> Starting php-fpm... \n"
exec "$PHP_RUN"
