FROM php:7-fpm-alpine

LABEL maintainer="Royee <ms_save95@126.com>"

# profile
ENV PATH="~/.composer/vendor/bin:/usr/local/entrypoint:$PATH" \
    # sshd
    SSH_ENABLED='no' \
    SSH_ROOT_PASSWORD='' \
    # composer
    COMPOSER_PACKAGIST='' \
    COMPOSER_ALLOW_SUPERUSER='no' \
    # laravel
    LARAVEL_ENABLED='no'

RUN set -xe \
    # china mirrors
    && sed -ri 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    # copy php.ini
    #&& cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini \
    #&& cp /usr/local/etc/php/php.ini-production /usr/local/etc/php/php.ini \
    \
    # php runtime
    && apk add --no-cache bash openssh libmcrypt freetype libjpeg-turbo libpng \
    # install compiling env
    && apk add --no-cache --update --virtual .build-deps \
                autoconf libc-dev gcc make git \
                libmcrypt-dev \
                freetype-dev libjpeg-turbo-dev libpng-dev \
    \
    # install PHP Bundled
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip pdo_mysql bcmath json mbstring exif fileinfo \
    \
    # install PHP extensions
    # memcached
    && apk add --no-cache libmemcached-dev zlib-dev \
    && pecl install memcached-3.0.4 && docker-php-ext-enable memcached \
    \
    # other
    && pecl install redis-4.1.1 && docker-php-ext-enable redis \
    && pecl install xdebug-2.6.0 && docker-php-ext-enable xdebug \
    \
    # clear
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/pear ~/.pearrc \
    \
    # Composer
    && wget https://getcomposer.org/composer.phar -O /usr/local/bin/composer \
    && chmod a+x /usr/local/bin/composer \
    && composer clear-cache

# source files
COPY ./entrypoint /home/tmp/entrypoint

RUN set -xe \
    # Entrypoint
    && chmod a+x /home/tmp/entrypoint/* \
    && mv /home/tmp/entrypoint /usr/local/entrypoint \
    \
    # clear
    && rm -rf /home/tmp