FROM php:7-cli-alpine

LABEL maintainer="Royee <ms_save95@126.com>"

# source files
COPY download /home/tmp/download

RUN set -xe \
    # china mirrors
    && sed -ri 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    # move php.ini
    && cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini \
    #&& cp /home/tmp/config/php56.ini-production /usr/local/etc/php/php.ini \
    \
    # php runtime
    && apk update && apk add --no-cache bash openssh libmcrypt freetype libjpeg-turbo libpng \
    # install compiling env
    && apk add --no-cache --update --virtual .build-deps \
                autoconf libc-dev gcc make git \
                libmcrypt-dev \
                freetype-dev libjpeg-turbo-dev libpng-dev \
    \
    # install PHP extensions
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install zip pdo_mysql bcmath \
    # memcached
    && apk add --no-cache libmemcached-dev zlib-dev \
    #&& pecl install memcached-3.0.4 \
    && pecl install /home/tmp/download/memcached-3.0.4.tgz \
    # other
    #&& pecl install redis-4.1.1 \
    #&& pecl install xdebug-2.6.0 \
    && pecl install /home/tmp/download/redis-4.1.1.tgz \
    && pecl install /home/tmp/download/xdebug-2.6.0.tgz \
    && docker-php-ext-enable memcached redis xdebug \
    \
    # clear
    && apk del .build-deps \
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/pear ~/.pearrc \
    \
    # clear
    && rm -rf /home/tmp

#CMD ["php-fpm"]